name: Vimal's Lab
title: Vimal's Lab
description: ""
theme: jekyll-theme-hacker
author: "vimal.shekar"
permalink: /blog/:year/:title
comments: True
pages_list:       
  About: '/README'
  My Blog: '/blog'
plugins:
  - jekyll-sitemap